### ISSUE TITLE
Support for SOAP APIs

### ISSUE THREAD

**Issue by kimitj** [apimanagement/drupalportal#2]
I noticed when I did look at my SOAP APIs through the developer portal that it converts the request/response to REST......

However, my provider is expecting SOAP..... so it fails when it hits the open {

Just wondering if someone could confirm if this is only for REST as took a while to get this up and running today :)

**Comment by evanskinner** [comment]
Yes I'm afraid that the UI only supports JSON REST APIs at the moment. We used swagger UI to provide the GUI components for displaying APIs and it doesn't have SOAP support yet.

**Comment by chrisdudley** [comment]
The portal will display information about SOAP APIs, there is just no live test support for them yet.

**Comment by chrisdudley** [comment]
Really should have closed this some time ago, support for live testing SOAP APIs was added some time ago. Sorry!
